src/fundus/publishers/de/__init__.py

This one caused a nasty bug where fundus stopped running because the zeit filtered all urls.

Fixes a broken regex in the Zeit url filter

---

README.md
docs/1_getting_started.md
docs/2_the_article_class.md
docs/3_how_to_filter_articles.md
docs/4_how_to_search_for_publishers.md
src/fundus/parser/data.py
src/fundus/scraping/filter.py

This adds missing tutorials for the library, updates the README.md, and adds some more logic to the filter behavior. 
The tutorials are:
1. Getting started
2. The Article class
3. How to filter articles
4. How to search for publishers
The changes made to the filter logic include.
- adding logic operators (or, and) to combine filters
**_NOTE:_** I'm not fully satisfied with how it is right now, but I'm fine with it. It still seems a bit complicated, but writing tutorial number three made it very obvious that we need something to combine filters. 
closes #198

Add missing tutorials

---

src/fundus/parser/utility.py
tests/resources/parser/test_data/de/FAZ.json

This solves an issue encountered with #264 by hardcoding UTC offsets for the timezone identifier CET, CEST. We needed to do so because the previous implementation which utilizes `dateutil.tz.gettz()` returns different results on different OS'.

GH264: Hardcode utc offsets

---

src/fundus/scraping/pipeline.py

This is already fixed with #271, but since that PR is postponed, this PR will fix the issue additionally.
This PR also sets the default delay used to 0.1 seconds to ensure Fundus uses polite request frequencies when crawling small amounts of publishers.

Fix a bug when using float as value for `delay`

---

src/fundus/publishers/us/the_nation_parser.py

As mentioned by @lukasgarbas within #275, `TheNation` consists of many JS within the extracted code. While #275 asked for a quality check in general, this PR solves the issue only specific to `TheNation`. Quality control should still be a thing coming to Fundus.
After a really long hunt, I finally found what was causing the extraction noise and learned a lot about HTML5. In short, the DOM layout `The Nation` uses isn't HTML5 compliant. There are two things especially annoying.
1. The site uses `<p>` tags within `<h*>` tags which isn't allowed according to [w3c](https://www.w3.org/TR/2014/REC-html5-20141028/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), judging by [this](https://stackoverflow.com/a/19779520) comment. This causes the `lxml.html` parser to fail since it is built …

Improve text extraction for `TheNation`

---

src/fundus/scraping/html.py
src/fundus/scraping/scraper.py

This makes the `HTMLSource` non-blocking alongside the also non-blocking scraper. We do so in order to be able to distribute load across publishers when using extensive URL filters. Before, when having a strict filter in place, and because of the blocking nature of `HTMLSource`, the crawler would search through an entire publisher until getting a hit, rather than search through the publishers equally.

Makes `HTMLSource` non blocking

---

docs/2_the_article_class.md
docs/how_to_contribute.md

This resolves the second point of #297. There will be a major rework of the entire `ArticleBody` and everything related, so the documentation proposed here is only the bare minimum.

GH297: Introduce `ArticleBody` and `ArticleSection` within the tutorial

---

README.md

This PR suggest some minor tweaks to the landing README page: 
- centered tagline and starting links, inspired from Fabricator
- made the "Fundus is.." part less verbose 
- made the "Quick Start" part less verbose by removing the "requirements and installation" subheader
- slightly expanded on the explanation of example 1

Landing page wording and style

---

.gitignore
setup.cfg
src/fundus/__init__.py

This PR makes some last adjustments in order to proceed with github and pypi release 0.1.0:
- fix version number; now `0.1.0`
- ignore `.pypirc` file
- remove `basic_logger` from `fundus.__init__`

Prepare version 0.1.0 release

---

docs/3_how_to_filter_articles.md
src/fundus/scraping/pipeline.py

Problem: Accepting only fully extracted articles as a default slows down Fundus and also presents it in a bad way. Many articles only lack some authors or topics and one could argue that the main focus is about the body.
Solution: This PR tries to solve this by accepting articles with at least a title, body, and publishing date set, and thus loosening the default.

Change default value for `only_complete` parameter.

---

.github/workflows/publisher_coverage.yaml
README.md
pyproject.toml
scripts/publisher_coverage.py

This PR adds a script to execute a baseline real-time crawler validation. A problem with the current crawler unit tests is that the crawlers are only validated on pre-fetched articles. This script aims to check a publisher's availability and basic crawl results.
The tests include a real-time crawl for each publisher's news map and RSS Feed checking the received articles for attribute completeness. Note that this script does not check the attributes' correctness, only their presence. The resulting publisher coverage is then summarised in the output report.
To automate the publisher coverage script this PR includes an action that runs every day at 01:00 generating a badge containing the publisher coverage displayed in the README. See …

Publisher Coverage Script and Badge

---

src/fundus/scraping/pipeline.py
src/fundus/scraping/scraper.py

- Fixes a faulty default parameter for `crawl_async` making it unusable using default parameters.
- Fixes a bug that caused bugged parser with uncaught exceptions to occupy the pipeline making `PublisherCollection.de` almost unusable.

Two major bug fixes

---

src/fundus/parser/data.py

This fixes an issue within LD parsing that caused LD's without an `@type` property to raise an exception.
This will also fix issues with `TheIndependent` noticeable in the [coverage action](https://github.com/flairNLP/fundus/actions/runs/7496921585/job/20409726758).

Fix `LD` parsing

---

scripts/generate_parser_test_files.py
src/fundus/parser/base_parser.py

`base_parser.py`
- Added an exception if no valid parser could be found.
`gerenerate_parser_test_files.py`
- removed leftover `bar.update()`

Various bug fixes

---

tests/utility.py

This adds a utility function to easily get the parsed test articles for a specific parser.

Add utility to retrieve test articles

---

src/fundus/publishers/us/cnbc.py

Adjusts the CNBC paragraph selector slightly for better quality.
Example articles:
https://www.cnbc.com/2023/04/28/many-new-bitcoin-crypto-buyers-influenced-by-friends-why-to-be-cautious.html
https://www.cnbc.com/2024/02/22/americans-with-debt-putting-less-money-toward-credit-card-payments.html

Adjust paragraph selector for CNBC

---

src/fundus/publishers/us/fox_news.py

This adds a new `summary` selector as well as including paragraphs with optional `div.paywall` parent node.

Adjust paragraph selector for Fox News parser

---

docs/attribute_guidelines.md
docs/how_to_add_a_publisher.md
docs/supported_publishers.md
src/fundus/parser/base_parser.py
src/fundus/publishers/de/bild.py
src/fundus/publishers/de/braunschweiger_zeitung.py
src/fundus/scraping/scraper.py
tests/test_parser.py

As discussed, I have added the free_access attribute natively to all publishers and overwriting it in the, to my knowledge, only special case (Bild).

Add free access atrribute

---

src/fundus/parser/data.py
src/fundus/parser/utility.py

As #338 showed (see Focus/Nation) sometimes JS is extracted as text into the article. This is due to Fundus using a broad XPath expression `string()` to extract text from nodes. While this makes it fast and easy to extract text from subsequent nodes, it does not allow Fundus to skip tag types (like `<script>`) during text extraction.
To address this issue this PR implements:
- a new method `text_content(excluded_tags: List[str])` defined on `Node` to extract text only from non-excluded nodes down the path
- furthermore this PR adds a normalization function `normalize-space` to normalize spacing within all extracted text. Previously, extracted text was in a weird state between `raw` and `normalized`. The normalization is done with `' '.join(.split())`

Add functionality to exclude tags from extraction and normalize space

---

scripts/generate_parser_test_files.py

This adds a new parameter `-u` to `scripts.generate_parser_test_files`
This parameter enables one to specify a URL to be used as a test case, see #333 
The `-p` parameter is necessary if URL(s) are given and the order of given publishers corresponds to the order of given URL(s).

Add URL parameter to test generation script

---

src/fundus/publishers/us/the_nation_parser.py

This fixes parsing for the nation once again 🎉 
- Fixes malformed HTML with missing </div> closing tag
- Fixes new version couldn't parse older articles

Fix malformed HTML for `TheNation`

---

pyproject.toml
src/fundus/scraping/html.py

This PR is an answer to recent troubles with the `validators` package. It:
- excludes `validators`' version `0.23.x`
- logs invalid init URLs for `URLSource` as an error instead of raising them, taking leverage away from the `validators` package.

Exclude `validators` verions `0.23.x`, log `URLSource` with invalid URL as init parameter as error instead of raising.

---

.github/workflows/lint.yml
.github/workflows/publish-package.yml
.github/workflows/tests.yml

This workflow adds the following jobs that trigger on any release with [type](https://docs.github.com/en/webhooks/webhook-events-and-payloads#release) `released`.
Jobs:
1. Test/Lint using existing workflows
2. Build distribution
3. Upload to TestPyPi
4. Test installation from TestPyPi
5. Upload to PyPi

Add release workflow to automatically publish on PyPi

---

src/fundus/publishers/de/business_insider.py
tests/resources/parser/test_data/de/BusinessInsider.json

As requested, I have opened in new PR containing the changes from and closing #376  , including changes to the paragraph and summary selector to also include an alternative layout in premium articles: https://www.businessinsider.de/wirtschaft/finanzen/ich-habe-meinen-job-mit-52-jahren-gekuendigt-und-lebe-seitdem-von-den-dividenden-auf-diese-aktien-setze-ich-dabei/ 
Since the changes include changing the way the title is parsed I had to modify the JSON accordingly.

This is a renewed PR for BI Germany, that keeps the mostly Test files unmodified

---

docs/supported_publishers.md
src/fundus/publishers/de/__init__.py
src/fundus/publishers/us/__init__.py

Including:
- `TAZ`
- `NTV`
- `APNews`
- `TheIntercept`
- `FreeBeacon`

Fix domains for several publishers

---

docs/supported_publishers.md
src/fundus/publishers/at/__init__.py
src/fundus/publishers/base_objects.py

Closes #345 
and has the following behavior:
`print(PublisherCollection)` prints
```python
The entire Publisher Collection consists of 38 publishers from 6 countries:
na:
The Namibian
de:
Die Welt
Mitteldeutscher Rundfunk (MDR)
Frankfurter Allgemeine Zeitung
Focus Online
Münchner Merkur
Süddeutsche Zeitung
Spiegel Online
Die Zeit
Berliner Zeitung
Tagesschau
Deutsche Welle
Stern
N-Tv
Norddeutscher Rundfunk (NDR)
Die Tageszeitung (taz)
Bild
Westdeutsche Allgemeine Zeitung (WAZ)
Braunschweiger Zeitung
Business Insider
at:
Österreichischer Rundfunk
us:
Associated Press News
CNBC
The Intercept
The Gateway Pundit
Fox News
The Nation
The Washington Free Beacon
The Washington Times
The New Yorker
Reuters
Occupy Democrats
Los Angeles Times
uk:
The Guardian
The Independent
The Telegraph
i
fr:
Le …
```

Adds Pretty Print for PublisherCollection and PublisherSpec

---

pyproject.toml
src/fundus/parser/data.py

Since `types-lxml` recent [update](https://pypi.org/project/types-lxml/2024.4.14/) doesn't seem to be compatible with `mypy 1.1.1` this PR bumps `mypy` to version `1.9.0` and removes a deprecated function in the process.

Bump `mypy` to version 1.9.0

---

scripts/generate_parser_test_files.py

I noticed that the attributes paramater of the `scripts.generate_parser_test_files` script, does not work properly or at least does not work as the others do. I updated this to have the default syntax which requires the user to input the parameters:
`--attributes attr1 att2 attr3` or `-a attr1 attr2 attr3`

Attributes Parameter in Test Generation Script

---

.github/workflows/documentation.yaml
.github/workflows/lint.yml
.github/workflows/publisher_coverage.yaml
.github/workflows/tests.yml

Since node 16 is deprecated, this PR updates all relevant actions to versions utilizing node 20.

Update relevant actions to versions utilizing node 20

---

scripts/generate_parser_test_files.py

Fixes a bug where the script will crash when no attributes are given.

Fix a bug in generate_parser_test_files.py

---

src/fundus/scraping/article.py

Unfortunately, we forgot to add the `free_access` attribute, which was introduced in #362, to the `Article` class. This PR finally addresses this issue.

Add `free_access` as attribute to `Article`

---

src/fundus/parser/data.py

There was a nasty bug in `LD.bf_search` basically rendering the parsing of boolean values unusable. This PR fixes this issue by introducing a new sentinel value and fixing some logic bugs.
One problem this could cause is that now the `free_access` attribute finally works as intended and this may cause some trouble since the publishers won't set it honestly.
Update: I opened another PR #423 to address this

Fix a bug in bf_search regarding boolean values

---

docs/3_the_article_class.md
docs/how_to_add_a_publisher.md

This adds a part to the documentation encouraging users to run 
```shell
python -m scripts.generate_tables
```
before opening a PR. In addition I fixed some errors in the docs as well.

Adds a part about `generate_tables` script to the documentation

---

src/fundus/publishers/us/business_insider.py

After discovering a bug that BI US sometimes prints incomplete articles, the closest @MaxDall and I got to tracing the issue is that there seems to be some kind of error within the authentication of premium users of the US bi website. The incomplete version is a slight modification of the complete version, where the main content is within another div container, which is blocked from view, when using a browser. What triggers whether or not they ask for a premium login could not be determined. So, the workaround is to expand the selectors to cover both cases.

bi authentication bug workaround

---

scripts/generate_parser_test_files.py
scripts/publisher_coverage.py
src/fundus/scraping/crawler.py
src/fundus/scraping/filter.py
tests/test_filter.py

With #422, 'free_access' is computed correctly. Because not all publishers set this information correctly, I felt the need to rework the extraction filter again. 
- I added a new parameter to `Requires`, `skip_boolean` which enables one to skip boolean values for evaluation
- There are now two predefined extraction filters: `Requires`, `RequiresAll`,
- `RequiresAll` is a name wrap for Requires() and propagates the `skip_bool` parameter to the user.

Rework `ExtractionFilter` to adept to boolean values

---

docs/how_to_add_a_publisher.md

Quite a lot of new contributors overwrite their existing test cases when slightly modifying their parser. I think we can counteract this by simply adding a part about `-oj` flag to the documentation.

Add a part about overwriting unit tests in how_to_add_a_publisher.md

---

src/fundus/publishers/de/__init__.py
src/fundus/scraping/url.py

- catches `HTTPError`s when requesting an `RSSFeed` 
- with #440 `Focus` now denies access to their RSS feed. This PR changes the user-agent used for `Focus` back to `Fundus`

Catch an error regarding `RSSFeed` and change `user-agent` for `Focus`

---

src/fundus/parser/base_parser.py
src/fundus/parser/data.py
src/fundus/publishers/base_objects.py
src/fundus/scraping/article.py
src/fundus/scraping/html.py
src/fundus/scraping/scraper.py
src/fundus/scraping/url.py
tests/test_parser.py
tests/utility.py

Additionally this re formats some logging messages.
closes #276

Use `!r` instead of single quotes for strings in f-strings

---

src/fundus/scraping/scraper.py

It seems that the url_filter defined in the PublisherSpec is ignored at the moment. This PR should take care of that.

Fix URL Filter Bug

---

.gitignore

I stumbled over quite a lot of PRs accidentally adding these files. They [seem](https://en.wikipedia.org/wiki/.DS_Store) to be part of MacOS' file system.

Add `.DS_Store` to `gitignore`

---

scripts/generate_parser_test_files.py

This is just a minor change, but it since the overwrite flag is verified before the JSON data is loaded, it allows us to overwrite the JSON, even if the JSON is malformed for whatever reason. With the former version, the JSON would first be loaded and cause an Exception if it was malformed. First seen in #466

Rearrange If Statement

---

scripts/generate_parser_test_files.py
tests/utility.py

Previously, when using `-o` option to overwrite existing test cases, the HTML file and meta.info entry had to be removed by hand. This PR automates that step.

Remove previous file when using `-o` option in test case script

---

scripts/publisher_coverage.py
scripts/utility.py

This adds a new timeout wrapper to publisher coverage enabling Fundus to use `Sitemap`s for coverage as well.

Add timeout to publisher_coverage.py

---

.github/workflows/publisher_coverage.yaml

Currently, the Publisher Coverage action fails because it can't find the `scripts.utility` module. Setting the PYTHONPATH correctly should fix this.
Traceback:
```
Traceback (most recent call last):
File "/home/runner/work/fundus/fundus/scripts/publisher_coverage.py", line 16, in <module>
from scripts.utility import timeout
ModuleNotFoundError: No module named 'scripts'
````

Set PYTHONPATH to the Root of the Repository for the Publisher Coverage Actions

---

src/fundus/parser/base_parser.py
src/fundus/publishers/de/freiepresse.py
src/fundus/publishers/na/the_namibian.py
tests/resources/parser/test_data/de/FreiePresse.json

When working with Fundus I found that way too much JSON is extracted when computing the self.precomputed elements. This causes multiple issues: 
- unnecessary but malformed JSON blocks cause avoidable crashes
- Additional JSON Blocks may cause irrelevant data to be extracted (e.g. the website (not article) author of the freiepresse test case: https://www.freiepresse.de/chemnitz/chemnitzer-hutfestival-wann-das-fest-steigt-was-neu-ist-und-wer-fuer-eine-gute-show-sorgen-wird-artikel13351201)
All current parsers mention the type within their JSON, only the old version of TheNamibian did not follow that convention, hence the override.

Update LD Selector

---

docs/how_to_add_a_publisher.md
src/fundus/parser/utility.py
src/fundus/publishers/us/rolling_stone.py
tests/resources/parser/test_data/us/RollingStone.json

In the previous implementation, key collisions where just overwritten. With this PR, each value is stored individually. For ease of typing, we store multi values as a string by joining them on `,`
closes #336

Refactor metadata parsing to include multiple values using the same key

---

README.md
docs/3_the_article_class.md
docs/4_how_to_filter_articles.md
docs/5_advanced_topics.md
src/fundus/parser/data.py
src/fundus/scraping/article.py
src/fundus/scraping/crawler.py
src/fundus/utils/serialization.py

This PR adds a `to_json()` function to the Article class and adds the option to save all articles to file.
Closes #529

Add export feature for Articles

---

src/fundus/scraping/filter.py

Found some references to `skip_bool` from an earlier version and updated them accordingly

Documentation Fix `Requires`

---

src/fundus/scraping/crawler.py
src/fundus/scraping/html.py

This PR guards the download and streaming of specific WARC files by catching `requests.HTTPError`s and `fastwarc.stream_io.StreamError`s and logging the corresponding WARC path at `error` level. This is in order to prevent Fundus from crashing when something went wrong during the processing of an individual WARC file.
This PR also adds a naive retry mechanic, that tries to reload said WARC file every 30 * current try seconds. By default, it does so three times.

Guard download and streaming of WARC files

---

src/fundus/scraping/crawler.py

So as it seems `CC-NEWS` we also have to spread the parallel task as well to avoid `503` errors while crawling. I tested this on `Gruenau` and it seems to work just fine.

Spread parallel requests for `CCNewsCrawler`

---

src/fundus/scraping/crawler.py

The previous retry implementation calculated retries incorrectly, as well as ignoring `urllib3.exceptions.HTTPError`.

Fix upper bound for retries and catch `urllib3.exceptions.HTTPError`

---

README.md
docs/4_how_to_filter_articles.md
docs/5_advanced_topics.md
docs/6_logging.md
src/fundus/logging.py

This PR
- exposes all loggers in a dictionary called `loggers` mapping module name to logger
- adds a new utility function to easily add a handler to all existing loggers
- add a new tutorial about logging and update the documentation accordingly

Expose loggers and update documentation

---

src/fundus/scraping/crawler.py

This PR:
- adds a bar to display the progression of WARC file processing
- add a parameter to `CCNewsCrawler` to disable progress bars

Add progress bar for WARC file processing 

---

scripts/publisher_coverage.py

When going through the failed publishers, I that it is a bit tedious to find the problem of why a certain article is not being parsed and the publisher coverage fails for a certain article. Hence I added some lines to the output to give an idea of how serious the fail is: e.g. there are no authors -> probably none given in the article and can just be ignored. No title or no plaintext -> something weird is going on and should be checked out. And also, we would know exactly where to look.

Show details about incomplete articles in Publisher Coverage

---

docs/supported_publishers.md
src/fundus/publishers/us/__init__.py

The sitemaps are inaccessible due to the website asking for login credentials. Weirdly enough, you even need credentials to read the articles as a normal visitor...

Mark Occupy Democrats as deprecated 

---

src/fundus/logging.py
src/fundus/scraping/crawler.py
src/fundus/utils/serialization.py

Previously, when using `spawn` as a start method, already set logging configurations are overwritten, when starting a new process. This PR introduces a workaround, passing the current configuration to the `Pool` and initializing the logging module with said config when a new process is started for the `CCNewsCrawler`.
IMO adding handlers and setting levels was still pretty tedious, even after the last rework. With this PR, the logger debug level is set to `DEBUG` by default, and one controls debugging with handler levels instead of the logger level.

Rework logging and fix overwritten config

---

src/fundus/publishers/de/freiepresse.py
tests/resources/parser/test_data/de/FreiePresse.json

The paragraph selectors seem to always have missed at least a paragraph. Now, with FP changing most of their articles to Premium only, the only free articles are just on paragraph long, which was then not parsed properly. It should work now, the test file was updated accordingly.

Fix Freie Presse

---

src/fundus/scraping/crawler.py

This PR adds some randomness to the waiting time in between retries. This is especially useful to avoid connection bulks after a connection loss. Previously, every process would have the same delay, resulting in all of them trying to reconnect at almost the same time after a connection loss, stressing the CC-NEWS server.

Stretch retries to avoid bulks after connection loss

---

src/fundus/publishers/de/braunschweiger_zeitung.py
src/fundus/publishers/de/hamburger_abendblatt.py
src/fundus/publishers/de/morgenpost_berlin.py
src/fundus/publishers/de/waz.py

Apparently the newpapers belonging to the Funke group have discontinued using the keywords keyword. For bigger articles they now have suggestions for similar categories, I would propose using these as new topics.

Fix Funke topics

---

pyproject.toml

Release: v0.4.0 🎉
With the merge of #560, we are excited to announce the release of a new major version: 0.4.0.
Unfortunately, this release has taken a while, resulting in new features being accessible only through the master branch. Moving forward, we want to maintain a more frequent release cycle to ensure timely access to new features and improvements 🚀.
Happy crawling :)

Bump version to `0.4.0`

---

docs/supported_publishers.md
src/fundus/publishers/us/__init__.py

Unfortunately, another US publisher became unreachable. Maybe someone could figure out a solution.

Set `WashingtonPost` deprecated

---

docs/6_logging.md

Any `FileHandler` is required to have a name (refer to fundus.logging.py). To be more consistent I added this to the logging documentation.

Add mandatory `set_name` to logging documentation

---

README.md

Updates the README with the latest evaluation results from the [evaluation repository](https://github.com/dobbersc/fundus-evaluation/releases/tag/v0.2.0).

Update Evaluation Results

---

.github/workflows/publisher_coverage.yaml

The current schedule time (01:00) negatively impacts the certainty of coverage results of some german (i.g. European) publishers.
This PR tries to set a schedule time that is more "during the day" for most publishers, ensuring RSSFeeds are working properly.

Change coverage schedule time to `14:00`

---

src/fundus/scraping/url.py

This fixes a bug regarding RSS feeds.
While parsing the feeds and yielding resulting URLs, the current implementation is based on the assumption that every feed entry has at least a `link` field, which is not the case.
This PR guards the key access.
See [this](https://github.com/flairNLP/fundus/actions/runs/10616770184/job/29427987839#step:5:145) for further details.

Guard key access for RSSFeed entries

---

scripts/generate_parser_test_files.py
tests/test_parser.py

When overriding the parser test file data multiple times in a row, the script will delete the saved html every other time. Simply reordering the commands fixes this. Additionally I updated the error message to also reflect the publisher where it occured, even though it is visible by looking though the pytest summary as well, I thought this is simpler because all the necessary information is at the same place.

Fix bug in test file generation

---

pyproject.toml
scripts/generate_parser_test_files.py
src/fundus/publishers/base_objects.py
src/fundus/scraping/crawler.py
src/fundus/scraping/html.py
src/fundus/scraping/scraper.py

This PR finally implements `robots.txt` based filtering of URLs.
Unfortunately the stdlib implementation of the `RobotFileParser` seems to have trouble fetching some pages so I had to add additional dependencies.

Add `robots.txt` based filtering

---

scripts/publisher_coverage.py

With the introduction of a robots.txt parsed crawl-delay in #609, the coverage script won't work for publishers specifying said delay. Further, in disabled the entire robot's parser for the coverage script to prevent side effects.

Ignore `robots.txt` in coverage script

---

src/fundus/publishers/base_objects.py
src/fundus/scraping/html.py

As some publishers require `user-agent` set for request headers, this PR add the `HTML` request header to the `Robots` request.

Add `HTML` headers to `Robots.read()`

---

src/fundus/scraping/article.py

There is a bug in the evaluation of the `plaintext` property of `Article` so that the actual content of `ArticleBody` is not displayed unless it includes a paragraph.

Fix a bug with the `plaintext` property of `Article`

---

src/fundus/publishers/de/sportschau.py

The former summary selector was too broad, causing errors when paring articles like this one: https://www.sportschau.de/fussball/nationsleague/ein-wechselspiel-aus-licht-und-schatten,einzelkritik-dfb-102.html . The parsing crashed because the summary nodes are not restricted to the beginning of the article.

Fix Sportschau

---

pyproject.toml
src/fundus/parser/data.py
src/fundus/utils/serialization.py
tests/test_data.py

This PR enables developers to query a `LinkedDataMapping` using XPath expressions by adding a method called `xpath_search` to `LinkedDataMapping`.
For an example, please take a look at the [test cases](https://github.com/flairNLP/fundus/pull/614/files#diff-60fb0a496fe1cd67d38a04f3cfde59201fe9bff091439e2d07eb834e1ba62f3a).

Implement XPath queries for LDs

---

src/fundus/publishers/na/the_namibian.py
tests/resources/parser/test_data/na/TheNamibian.json

Occasionally, a `<br>` tag is used to start a new paragraph instead of the usual new `<p>` element. I have modified the `_base_setup` to replace these tags prior to processing the article. As an extreme example consider this article: https://www.namibian.com.na/namibian-disability-federation-urges-official-recognition-of-sign-language-for-deaf-inclusion/
The test case also contains one example.

Remove `<br>` tags in html

---

src/fundus/publishers/na/the_namibian.py

The author parsing crashed, if it encounters an article with more than author. This is caused that the element element with path Person can be of type `list`. in which case the `get()` function that is called within `get_value_by_key_path()` causes an Error, since it is not implemented for a list.

Fix bug in author parsing in `TheNamibian`

---

src/fundus/publishers/de/hessenschau.py

Extends the paragraph selector to also select other layouts. Also includes lists.

Fix `Hessenschau`

---

src/fundus/parser/utility.py
src/fundus/publishers/au/west_australian.py
src/fundus/publishers/na/the_namibian.py

This PR aims to make the code about LD and JSON parsing a bit less complex. Further, I removed some unused imports for `TheNamibian`

Cleaner code for LD and JSON parsing

---

src/fundus/publishers/de/focus.py

This PR adresses two issues:
- Some articles such as this one: https://www.focus.de/finanzen/karriere/gen-z-in-den-usa-zieht-handwerkliche-berufe-hochbezahlten-buerojobs-vor_eaf8f700-90ab-45ec-a1f3-8d1ac74faa86.html are not extracted at all, due to the layout being slightly different
- QSE is having trouble using the focus articles, due to topics being rarely used. I implemented a rough fallback, to use section keywords, what in my opinion is somewhat satisfactory, but perhaps @MaxDall you can also check, if it's worth adding them.

Fix `Focus`

---

pyproject.toml
src/fundus/parser/data.py
src/fundus/publishers/de/freiepresse.py
src/fundus/publishers/de/krautreporter.py
src/fundus/publishers/no/__init__.py
src/fundus/publishers/shared/euronews.py
src/fundus/publishers/us/ap_news.py
src/fundus/publishers/us/cnbc.py
src/fundus/publishers/us/occupy_democrats.py
src/fundus/publishers/us/reuters.py
src/fundus/publishers/us/the_gateway_pundit.py
src/fundus/publishers/us/the_intercept.py
src/fundus/publishers/us/the_new_yorker.py

This PR deprecates `get_value_by_key_path` class method of `LinkedDataMapping` and replaces all existing occasions with `xpath_search`.
To talk about efficiency I provide some additional runtime comparison and a script to reproduce.
The script loads one article for `The West Australian`, since it by far includes the largest `LD` and loads a specific value (or key path) 100000 times. For more details click on `Script`.
<details>
<summary>Script</summary>
```python
from timeit import timeit
setup = '''
from timeit import timeit
from fundus import PublisherCollection, Crawler
from lxml.etree import XPath
test_xpath = XPath("NewsArticle/datePublished")
crawler = Crawler(PublisherCollection.au.WestAustralian)
for article in crawler.crawl(max_articles=1):
ld = article.ld
'''
stmt1 = …
```

Deprecate `get_value_by_key_path` and replace with `xpath_search`

---

src/fundus/parser/data.py

As of now, the parsing of LD-JSON raises an error, when encountering an object with multiple types defined. I would suggest that, instead of prohibiting multiple values for ld_type, we combine them in a comma separated list. This (or another solution) is necessary for adding the Spanish Newspaper El Pais

Handle multiple ld types

---

src/fundus/parser/base_parser.py
src/fundus/scraping/article.py
tests/test_parser.py

This PR 
- fixes a bug where attributes annotated with `Optional` raised an error when parsing a default value
- adds a parameter `default_factory` to `attribute` so that one can set a default for `Union`s which do not include `None`
- adds a test case to test default values for attributes

Fix a bug with attribute defaults and add `default_factory` parameter

---

src/fundus/publishers/de/boersenzeitung.py
tests/resources/parser/test_data/de/BoersenZeitung.json

The former version could not parse subheadlines from some articles, e.g. https://www.boersen-zeitung.de/kapitalmaerkte/steigende-us-zinsen-setzen-dax-zu 
Furthermore, it slipped our view that the summary_selector was unused

Fix `BoersenZeitung`

---

src/fundus/publishers/de/merkur.py

This ensures that the summary is at the beginning of the article. It was problematic in this article: https://www.merkur.de/lokales/landsberg-kreisbote/arbeitsgericht-am-klinikum-landsberg-wiedereingliederung-abgelehnt-hausverbot-erteilt-dr-urs-abker-zieht-vors-92079609.html

Fix `Merkur`

---

docs/supported_publishers.md
src/fundus/parser/utility.py
src/fundus/publishers/de/__init__.py
src/fundus/publishers/de/freiepresse.py
src/fundus/publishers/de/gamestar.py
src/fundus/publishers/de/golem.py
src/fundus/publishers/de/heise.py
src/fundus/publishers/de/hessenschau.py
src/fundus/publishers/de/junge_welt.py
src/fundus/publishers/de/kicker.py
src/fundus/publishers/de/krautreporter.py
src/fundus/publishers/de/mz.py
tests/resources/parser/test_data/ca/NationalPost.json
tests/resources/parser/test_data/ch/SRF.json
tests/resources/parser/test_data/de/DieWelt.json
tests/resources/parser/test_data/de/FAZ.json
tests/resources/parser/test_data/de/Golem.json
tests/resources/parser/test_data/de/Heise.json
tests/resources/parser/test_data/de/Hessenschau.json
tests/resources/parser/test_data/de/Kicker.json
tests/resources/parser/test_data/de/MitteldeutscheZeitung.json
tests/resources/parser/test_data/no/Dagbladet.json

I suggest the following changes:
- sort by float value (I had a case using 1.5x)
- use the ancestor function of XPath to get the parent picture element, should it exist. This has the advantage that if it exist, it will actually be found. In the previous version, `.getParent()` would select the predecessor, which is not necessarily the parent, as one would expect it to be (thinking of a tree structure).
_Only the utility.py should be worth going through. If you look at the commit with the changes to utility, you will see the difference the second bullet point causes._

Minor Changes to Utility Functions

---

src/fundus/publishers/de/frankfurter_rundschau.py

This PR adds parsing for this article: https://www.fr.de/ratgeber/tiere/zeitumstellung-tiere-haustiere-hunde-katzen-wildtier-landwirtschaft-tagesrhythmus-zr-93379931.html

Fix `Frankfurter Rundschau`

---

src/fundus/publishers/fr/__init__.py

I looked for a back-up since the Sitemap and NewsMap are currently unavailable or empty. I added the two broadest Feeds offered by Le Figaro

Add RSSFeed to `LeFigaro`

---

src/fundus/scraping/url.py

Adds a new content-type to the decompressor to decompress `octet-streams`. Previously sitemaps like for `lt.LRT` couldn't be read.

Add `octet-stream` to decompressor

---

src/fundus/parser/data.py
src/fundus/parser/utility.py
src/fundus/publishers/at/derstandard.py
src/fundus/publishers/de/die_welt.py
src/fundus/publishers/tr/ntvtr.py
src/fundus/publishers/uk/express.py
src/fundus/publishers/uk/the_bbc.py
src/fundus/publishers/uk/the_independent.py
src/fundus/scraping/crawler.py
src/fundus/utils/regex.py
src/fundus/utils/serialization.py

This PR reworks the versioning system of images, adds extended serialization and parses size for image versions.

add version parsing

---

src/fundus/parser/data.py

Previously, when parsing LDs including "empty" entries (i.e., `'authors': []`), `xpath_search` would return actual None values.
This PR fixes that behavior by filtering values on a boolean condition beforehand.

Fix a bug returning `None` for empty values in `xpath_search`

---

scripts/publisher_coverage.py

Since images will also now be required in the testing of the publisher coverage as per `RequiresAll()`, I updated the script to also provide feedback on it's existence as well

Update publisher coverage

---

src/fundus/scraping/article.py
src/fundus/scraping/crawler.py

There was a bug when serializing the `images` attribute described in #702. This PR provides a quick fix so that the `to_json` method also works for `images`.

Fix article serialization for `images`

---

docs/supported_publishers.md
src/fundus/publishers/uk/__init__.py

The sitemaps of `TheTelegraph` are no longer reachable by `Fundus`

Deprecate `TheTelegraph`

---

src/fundus/publishers/us/__init__.py

This PR:
- removes the NewsMap that only contains irrelevant pages
- filters the irrelevant pages from the remaining sitemaps
The pages filtered are similar to this page: https://voanews.com/a/8003948.html (will be redirected)

add url_filter to voa

---

src/fundus/publishers/dk/jyllands_posten.py

This PR adds the meta attribute ˋauthorˋ as a fallback in author parsing for the publisher ˋJyllandsPostenˋ.

Update author extraction for ˋJyllandsPostenˋ

---

src/fundus/parser/utility.py

The Publisher Coverage caught an error for this article: https://freebeacon.com/trump-administration/trump-slaps-tariffs-on-colombia-after-its-israel-bashing-marxist-president-rejects-us-deportation-flights/. It turns out that the reason is that the unicode symbol `\u202f` is embedded in the links of the second image, which for some implementations of regex (also apparently of the `re` package) is covered under `\s`, where as for others it is not leading to unpredictable behavior. I'm not really sure, whether to fix it or let this article slide. Then again, not sure how common the issue is. You can observe the issue here: https://regex101.com/r/rv9Zxp/1 You see this matcher does not find any matches (at least in Chrome), if you then go to regexr.com and use the pattern `\s` on this …

Remove Whitespace Normalization in image source parsing

---

src/fundus/publishers/au/west_australian.py
src/fundus/publishers/be/__init__.py
src/fundus/publishers/cz/seznamzpravy.py
src/fundus/publishers/de/br.py
src/fundus/publishers/de/dw.py
src/fundus/publishers/de/heise.py
src/fundus/publishers/de/hessenschau.py
src/fundus/publishers/de/netzpolitik_org.py
src/fundus/publishers/de/sz.py
src/fundus/publishers/es/abc.py
src/fundus/publishers/ind/__init__.py
src/fundus/publishers/it/__init__.py
src/fundus/publishers/it/il_giornale.py
src/fundus/publishers/no/dagbladet.py
src/fundus/publishers/no/nettavisen.py
src/fundus/publishers/pl/rzeczpospolita.py
src/fundus/publishers/shared/euronews.py
src/fundus/publishers/tz/__init__.py
src/fundus/publishers/us/cnbc.py
src/fundus/publishers/us/fox_news.py
src/fundus/publishers/us/free_beacon.py
src/fundus/publishers/us/la_times.py
src/fundus/publishers/us/the_gateway_pundit.py
src/fundus/publishers/us/the_new_yorker.py
src/fundus/publishers/us/wired.py
tests/test_publisher_collection.py
tests/utility.py

A minor clean up of the code base removing unused imports from `./src`, `./tests`, and `./scripts`

Remove unsued imports

---

src/fundus/publishers/de/__init__.py

@addie9800 Just to add—since this publisher no longer supports `topics`, it might be worth implementing a way to expire specific attributes instead of creating a new version. Maybe you'd like to give it a try?

Fix `Focus` sources

---

src/fundus/scraping/scraper.py

This bug causes Fundus to crash, when `restrict_sources_to` contains a `URLSource` which is not supported by one of the publishers. This PR handles that case.

Bug Fix in Source Restriction

---

src/fundus/publishers/de/zdf.py

The previous selectors couldn't parse the `summary` and `subheadline` nodes for articles like [this](https://www.zdf.de/nachrichten/politik/ausland/ukraine-russland-konflikt-blog-102.html).

Adjust `ZDFParser` to be more suitable for live tickers

---

.github/workflows/publisher_coverage.yaml
scripts/publisher_coverage.py
src/fundus/parser/utility.py
src/fundus/scraping/crawler.py
src/fundus/scraping/session.py
src/fundus/scraping/url.py

During the debugging of the publisher coverage, several issues arose:
- We spend unnecessary amount of time crawling publishers in the publisher coverage, where the action bot is blocked
- We cannot deal with urls that are of the form `www.test.de%2Fthis-is-the-site.html` 
- We cannot properly parse JSON with line breaks within strings (occurs when crawling `FreiePresse`).
This PR adresses these three issues.
Update:
The final commit adds the following further changes:
- Call `task_done()` on `response_queue` solving the main deadlock issue
- Fixes a bug, where if a sitemap only contains a newline character, it is not detected as an empty sitemap, causing Fundus to crash
- Moves the `pool` out of the context manager setup, because the later call of `pool.join()` can cause unexpected …

Bug Fixes from Publisher Coverage

---

src/fundus/scraping/crawler.py

```
from fundus import PublisherCollection, Crawler
crawler = Crawler(PublisherCollection.us.FreeBeacon, restrict_sources_to=[NewsMap, RSSFeed])
for article in crawler.crawl(max_articles=10, only_complete=False):
print(article)
```
The code above will exit without any output with the current Fundus version. This leads to quite a headache, when debugging, which is why I propose adding a warning-level log if a publisher is found to not have any sources that fit the specified filters.

Add logging for source restriction

---

src/fundus/publishers/jp/__init__.py
src/fundus/publishers/jp/nikkei.py

As it seems, there no longer a sitemap available, that we can use. Also no RSSFeeds and NewsMaps available anymore. Please double-check whether you can find anything, I was unable to. There are some for subdomains, such as asia.nikkei.com, but they have a completely different layout, which would require a completely new parser.

Deprecate ˋNikkeiˋ

---

src/fundus/scraping/url.py

The publisher coverage was failing due to malformed XML in `TheGatewayPundit`. Proposed fix:
- Allow for heuristic recovery through `lxml.etree.XMLParser` 
- Catch failing instances and log a warning

Handle malformed XML
