- scripts/generate_parser_test_files.py
- src/fundus/parser/data.py
- src/fundus/scraping/html.py
- src/fundus/scraping/scraper.py
This PR resolves #257 by replacing warn with warning across the whole codebase. 
Closes #257
> GH257: Replaces logging.warn with logging.warning

- src/fundus/publishers/us/__init__.py
So apparently APNews changed their sitemap layout and address. 
Edit: It seems that they also use a new layout. I will do a fix with this PR.
Edit2. I decided to try another approach for versioning these small fixes. See #281
> Fix APNews

- docs/3_how_to_filter_articles.md
This is one of the bullet points in #297. This filter is a bit more complex, but should work most of the time in a timely manner.
> Removes the donald duck filter and replaces it with a better example

- src/fundus/parser/utility.py
This fixes several bugs within the article body creation. Most of them a due to bad design. There should be a rework of the entire logic. This is just a fix first and foremost.
> Fix a bug within article body creation

- src/fundus/publishers/us/__init__.py
This further updates sitemap configs of `TheNation` to improve usability.
> Enhance sitemap config for `TheNation`

- docs/how_to_contribute.md
This solves the third point of #297
> GH297: Rewrite documentation section about adding sources.

- docs/how_to_add_a_publisher.md
- docs/how_to_contribute.md
This solves the 5th point of #297
> GH297: Add tutorials for CSSSelect and XPath

- setup.cfg
- src/fundus/scraping/html.py
This PR is based on #271 
Adds the following:
- Detailed log message when an exception is encountered during a request.
- Status code chain for redirected requests in the log message.
- Decrease overall connection timeout from 300 -> 30 seconds.
> Improve logging and decrease connection timeout

- src/fundus/publishers/uk/__init__.py
This adds a new filter to `TheIndependent`'s sitemap to avoid article hubs.
> Update `TheIndependent`'s sitemap

- src/fundus/scraping/pipeline.py
- src/fundus/utils/more_async.py
This:
- adds a new class `AsyncRunner` to `more_async.py` which handles an event loop
- replaces existing logic in `crawl()` with runner
> Replaces former logic in `crawl` with runner

- README.md
- pyproject.toml
- updates Fundus to version 0.2.0
- makes the logo path absolute to load in pypi
New Features etc. will be done in the release.
> Bump up version to 0.2.0

- README.md
- docs/2_crawl_from_cc_news.md
- docs/3_the_article_class.md
- docs/4_how_to_filter_articles.md
The fixes the broken tutorial links which where introduced with #331
> Fixes broken tutorial links

- src/fundus/publishers/de/die_zeit.py
I updated the paragraph selector, but I didn't add a new parser version due to the new XPath variant being more or less equivalent to the previous CSSSelector().
> Fiz zeit paragraph selector

- docs/supported_publishers.md
- src/fundus/publishers/us/__init__.py
Because #357 takes some time i temporarily comment out unreachable `WorldTruth`.
> comment out `WorldTruth` from the collection

- pyproject.toml
This prepares a new release in order to ship #400
> Bump version to 0.2.2

- scripts/publisher_coverage.py
Previously publishers were only rendered as success when providing articles with `free_access`. This wasn't done on purpose and made the coverage somewhat unreliable.
This PR adds a custom filter skipping boolean values.
Furthermore the script now skips publishers not providing either `NewsMap` or `RSSFeed`s.
> Add custom filter for `publisher_coverage` to skip boolean values

- .github/workflows/documentation.yaml
This hopefully :) fixes a bug with PRs from forks not finding the Fundus repo within the `documentation.yaml`.
> Fixed a bug in `documentation.yaml`

- .github/workflows/documentation.yaml
Fixes a bug with `documentation.yaml`
> Removes leftover workflow requirements

- README.md
- pyproject.toml
> Bump Fundus version to `0.3.0`

- tests/utility.py
This PR automatically adds meta info files generated for test cases to git.
> Add meta-info file automatically to git

- src/fundus/scraping/html.py
This PR adds encoding detection based on HTML. This is in order to replace `requests` default encodings when there is no `charset` property present in the response headers.
closes #446
> gh446: predict encodings for responses

- docs/how_to_add_a_publisher.md
This adds a small part about publishers using bot protection and how to verify the publisher one wishes to add doesn't
> Add part about un-crawl-able publishers

- src/fundus/scraping/html.py
This fixes two issues that i noticed while working on #444 
- sometimes `Content-Type` is used as lower case
- `lxml.html.document_fromstring` uses `utf-8` default to decode bytes which can lead to errors. We now use the `requests` fallback
> Fix some issues regarding encoding detection

- src/fundus/parser/utility.py
This raises an exception if summary nodes aren't at first place in the article.
> Raise `Exception` if summary is not first node

- docs/how_to_add_a_publisher.md
The previous code snippet had no `User-Agent` set which could lead to false negatives.
> Add header to bot protection snippet

- pyproject.toml
Preparation for release version `0.3.1`
> Bump version to `0.3.1`

- src/fundus/scraping/crawler.py
This adds a random sleep between 0 and 3 seconds in between requests for WARC paths to prevent `503` errors.
> Slow down WARC path requests

- src/fundus/publishers/uk/the_mirror.py
This PR updates the selectors to be more flexible and also includes live tickers.
> Fix The Mirror

- README.md
- docs/2_crawl_from_cc_news.md
- src/fundus/scraping/crawler.py
This PR ...
* reworks example 3 in the README to display a more realistic CC-NEWS use case
* add a message about optimal process count when using the default process count
* rework tutorial about `CCNewsCrawler` a bit
> Rework examples and tutorials regarding CC-NEWS

- src/fundus/__init__.py
- src/fundus/scraping/article.py
- src/fundus/scraping/scraper.py
- tests/test_article.py
- tests/utility.py
This PR presents a comprehensive overhaul of the Article class to improve data handling and maintainability.
- **Introduction of Data Views**: The refactor emphasizes maintaining raw extraction data as the primary source while providing structured `Views` for data access. This approach facilitates easier benchmarking and evaluation.
- **Implementation of Custom Attribute Handling**: Custom `__getattribute__` and `__setattr__` methods replicate Descriptor-like behavior, ensuring controlled attribute access without relying on class attributes.
- **Read-Only Attributes**: Initially, all extraction data is read-only to enhance security and stability. This simplifies data integrity management, with provisions for future writable features.
This PR serves as preparation for the upcoming CC-NEWS …
> Rework `Article` class

- README.md
Updates the paper URLs and bibtex citation to our ACL 2024 demo paper.
> Update Paper Citation to ACL

- docs/supported_publishers.md
- src/fundus/publishers/fr/__init__.py
> Deprecate blocked publishers

- .github/workflows/publish-package.yml
This PR ...
- adds verbosity to the `pypa/gh-action-pypi-publish@release/v1`
- dispatches the workflow (only with admin permissions)
> Add verbosity to and dispatch distribution workflow

- src/fundus/scraping/html.py
This adds an additional selector to the HTML encoding detection to avoid requests build-in detection. This is because the latter uses chardet which can lead to seriously long execution times (>3s) for a single article.
> Improve encoding detection

- scripts/publisher_coverage.py
This resolves a bug in the publisher coverage script where an `Exception` used as an attribute value for an article was not accounted for, causing the script to crash.
> Fix a bug in `publisher_coverage.py`

- scripts/publisher_coverage.py
- src/fundus/publishers/base_objects.py
- src/fundus/scraping/crawler.py
- src/fundus/scraping/html.py
- src/fundus/scraping/scraper.py
- src/fundus/scraping/session.py
- src/fundus/scraping/url.py
- src/fundus/utils/events.py
This PR ...
- fixes a race condition that prevented exceptions from being propagated
- makes open connections interruptible so the pool can properly shut down
- fixes the publisher scipt to run again
> Make network connections interruptible 

- scripts/generate_tables.py
- src/fundus/publishers/base_objects.py
- src/fundus/scraping/crawler.py
- tests/fixtures/fixture_collection.py
- tests/test_collection.py
This reworks parts of the language attribution PR, in particular, adding a new "aware" publisher object called `FilteredPublisher`
> Rework language attribution

- src/fundus/__init__.py
This PR fixes a bug with the `lang` attribute not being deterministic.
> Make `lang` attribute deterministic

- src/fundus/publishers/uk/the_bbc.py
Fixes and closes #748 by:
- modifying ˋsubheadline_selectorˋ
- modifying ˋsummary_selectorˋ
> Modify BBC selectors

- src/fundus/publishers/de/__init__.py
This PR updates the link for the RSSFeed.
> Update RSSFeed for `Bild`

- src/fundus/publishers/tz/__init__.py
This PR updates the `Sitemap` for `HabariLeo` and `DailyNews`
> Update Sitemaps for Tanzania

- src/fundus/publishers/tz/daily_news_tz.py
There were some minor layout changes that needed to be addressed
> Update Tanzanian publishers

- docs/supported_publishers.md
- src/fundus/publishers/pt/__init__.py
The sitemap URLs are outdated. I have now also added the sources for various available languages.
> Update sources ThePortugalNews
